{
 "title": "Bosch SmartHomeController",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Aktueller Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "actual_power_consumption", "legendFormat": "{{room}}" },
    { "expr": "sum(actual_power_consumption)", "legendFormat": "Summe" }
   ]
  },
  {
   "title": "Gesamtverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "total_power_consumption", "legendFormat": "{{room}}" },
    { "expr": "sum(total_power_consumption)", "legendFormat": "Summe" }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "room_temperature", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "room_humidity", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Rollladenposition",
   "type": "timeseries",
   "description": "0% - geschlossen\n100% - geöffnet",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "shutter_level", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Schalter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "switch_state", "legendFormat": "{{room}}" }
   ]
  }
 ]
}